num1 = int(input("please enter your first number"))
num2=int(input("please enter your second number"))
num3=int(input("please enter your third number"))
print("thanks!")
print(num1)
print(num2)
print(num3)
print(num1 + num2 + num3)
print(type(num1))
print(num1 * num2 * num3)
print(type(num1))